version: "3.8"

services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    network_mode: host

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Seoul
    network_mode: host

  nginx:
    image: "nginx:alpine"
    container_name: nginx
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
      - /home/ubuntu/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/letsencrypt/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
